project:
  type: book
  output-dir: docs
  
book:
  sidebar:
    style: floating # docked
    search: false
    title: Eduardo Armenta G. Version 1.0
    tools:
      - icon: github
        href: https://github.com/ModeEdna
      - icon: linkedin
        href: https://www.linkedin.com/in/eduardo-armenta/
      - icon: twitter
        href: https://twitter.com/EdnaMode07
      # - icon: mailbox
      #   href: eduardoarmenta95@gmail.com
  page-navigation: false
  #body-footer: Version 1.0
  #body-header: Version 1.0
  footer: version 1.0
  title: My Portfolio
  #author: Insert author name
  #description: Version 1.0
  #edition: 1.0
  version: 1.0
  #volume: 1.0
  #subtitle: Version 1.0
  date: 12/30/2022
  chapters:
    - index.ipynb
    - part: About Me
      chapters:
        - notebooks/resume.ipynb 
        - notebooks/packages.ipynb
        # - notebooks/contactInfo.ipynb
    - part: Grad School
      chapters:
        - notebooks/final501.ipynb
        - notebooks/final511.ipynb
        - notebooks/NLP_Final_Project.ipynb
    - part: Work Projects
      chapters:
        - notebooks/TAM2.ipynb
        - notebooks/tesoreria.ipynb
    - part: Base Python
      chapters:
        - notebooks/blackjack.ipynb
        - notebooks/tictactoe.ipynb
        - notebooks/cardgamewar.ipynb

format:
  html:
    theme:
      dark: darkly
      light: flatly
    number-sections: false
    #email-obfuscation: javascript
    #title-block-style: default
    #title-block-banner: false
    #title-block-banner-color: white
    link-external-newwindow: true
